export const REQUIRED_SALES_CHANNEL_KEYS = [
  'Direct',
  'Stripe',
  'Gumroad',
  'Fiverr',
  'Upwork',
  'Taskrabbit',
  'Freelancer',
  'PeoplePerHour',
  'Guru',
  'Contra',
  'Thumbtack',
  'Bark',
  'Houzz',
  'Etsy',
  'Shopify',
  'FacebookMarketplace',
  'FacebookBusinessPage',
  'Instagram',
  'TikTokShop',
  'TikTokProfile',
  'AmazonManual',
  'EbayManual',
  'WooCommerceManual',
  'GoogleBusinessProfile',
  'Craigslist',
  'Nextdoor',
  'Discord',
  'Skool',
  'Circle',
  'LinkedIn',
  'YouTube',
  'XTwitter',
  'Lemon8',
  'Pinterest',
  'ProductHunt',
  'IndieHackers',
  'AppSumo',
  'ChamberOfCommerce',
  'Yelp',
] as const;

export const REQUIRED_PACKAGE_KEYS = [
  'QuickCleanup10',
  'MarketplaceListing25',
  'MarketplaceListing50',
  'ProductLaunch50',
  'ProductLaunch100',
  'MonthlySellerRetainer',
  'AgencyWhiteLabel',
  'Custom',
] as const;

export const REQUIRED_PRESET_KEYS = [
  'AmazonMainImageDraft',
  'AmazonSecondaryImageDraft',
  'EtsyListingSquare',
  'EbayListingSquare',
  'ShopifyProductImage',
  'TikTokShopVertical',
  'InstagramSquare',
  'InstagramStoryReelVertical',
  'FacebookMarketplaceSquare',
  'PinterestPin',
  'WebsiteProductGallery',
  'GumroadProductOfferImage',
  'RestaurantMenuItemImage',
  'RealEstateListingCleanup',
  'CustomClientPreset',
  'TransparentPngCutout',
  'WhiteJpgCatalog',
] as const;

export type RequiredSalesChannelKey = (typeof REQUIRED_SALES_CHANNEL_KEYS)[number];
export type RequiredPackageKey = (typeof REQUIRED_PACKAGE_KEYS)[number];
export type RequiredPresetKey = (typeof REQUIRED_PRESET_KEYS)[number];
